spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AnimalWorld
    username: postgres
    password: 4747
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true