spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animal
    username: postgres
    password: 1208
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
